//! Native C ABI for webylib.
//!
//! Macro-generated by `#[ffi_export]` from a small set of Rust signatures
//! over the wallet-core API. Replaces the legacy 22K-LOC `src/ffi/wallet_ops.rs`.
//!
//! Owns its own tokio runtime; async surface via callback-or-blocking-wrapper
//! pattern. Cancellation by handle. Opaque handle types: `WebyWallet`,
//! `WebyServer`. WASM target does NOT depend on this crate.
//!
//! Implementation lands in M2.
