//! Native C ABI for webylib.
//!
//! Macro-generated by `#[ffi_export]` from a small set of Rust signatures.
//! Replaces the legacy 22K-LOC `src/ffi/wallet_ops.rs` with a single
//! source of truth.
//!
//! Each annotated Rust function emits a matching `extern "C"` shim:
//!
//! - sync `pub fn xxx(args) -> R` → `extern "C" fn weby_xxx(args) -> R`
//! - async `pub async fn xxx(args) -> Result<T, E>` → `extern "C" fn
//!   weby_xxx(args, *mut T) -> i32` with the result error-coded.
//!
//! The macro embeds a per-fn lazy tokio runtime so async functions can be
//! called directly from C.
//!
//! # Demo
//!
//! ```ignore
//! #[ffi_export]
//! pub fn add(a: i32, b: i32) -> i32 { a + b }
//!
//! // Generates `extern "C" fn weby_add(a: i32, b: i32) -> i32`.
//! ```
//!
//! See `tests/ffi_demo.rs` for an exercised end-to-end example.

#![allow(clippy::missing_safety_doc)]

use webylib_macros::ffi_export;

// ─────────────────────────────────────────────────────────────────────────────
// Demo: prove the macro round-trips end-to-end.
// ─────────────────────────────────────────────────────────────────────────────

/// Sum two i32s. Pure-sync, demonstrates scalar marshaling.
#[ffi_export]
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}

/// Identity on i64 — proves wider scalars round-trip.
#[ffi_export]
pub fn identity_i64(x: i64) -> i64 {
    x
}

/// Echo the byte-length of a borrowed string. Demonstrates `&str` →
/// `*const c_char` marshaling with NUL-checks.
#[ffi_export]
pub fn str_len(s: &str) -> i32 {
    s.len() as i32
}

/// Async function. Demonstrates the per-fn tokio runtime + Result<T, E>
/// → (i32, *mut T) marshaling.
#[ffi_export]
pub async fn double_eventually(x: i64) -> Result<i64, FfiError> {
    tokio::time::sleep(std::time::Duration::from_millis(1)).await;
    x.checked_mul(2).ok_or(FfiError::Overflow)
}

/// Async returning `Result<(), E>`. Demonstrates the unit-result path.
#[ffi_export]
pub async fn validate_positive(x: i64) -> Result<(), FfiError> {
    if x > 0 {
        Ok(())
    } else {
        Err(FfiError::NotPositive)
    }
}

#[derive(Debug, thiserror::Error)]
pub enum FfiError {
    #[error("overflow")]
    Overflow,
    #[error("not positive")]
    NotPositive,
}
